{% set name = "psij-zmq" %}
{% set version = "0.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/psij-zmq-{{ version }}.tar.gz
  sha256: 46d762e650558c57d9303a0e4f3b03cd8c64f957876eea8d7273bf5522c53dee

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - psij-python
    - pyzmq
    - radical.utils

test:
  imports:
    - psij

about:
  home: https://github.com/exaworks/psij-zmq
  summary: This is an implementation of the PSI/J (Portable Submission Interface for Jobs)
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
